# ((.Module)) module

This is a module for ((.DisplayName)) logs.

Autogenerated from RSA NetWitness log parser ((.LogParser.Version.Device)) XML ((.LogParser.Description.Name)) version ((.LogParser.Version.Revision))
at ((.GeneratedTime)).

